name: plsDonate
version: "1.0"
main: click.sattr.plsDonate.PlsDonate
api-version: "1.21"
commands:
  plsdonate:
    description: Main command for plsDonate
    aliases: [pdn]
    permission: plsdonate.admin.help
  donate:
    description: Main donation command
softdepend: [floodgate, Geyser-Spigot, Geyser, PlaceholderAPI, SkinsRestorer, ViaVersion]
permissions:
  plsdonate.donate.request:
    description: Create a donation request via /donate
    default: true
  plsdonate.donate.top:
    description: View the donation leaderboard
    default: true
  plsdonate.donate.milestone:
    description: View the donation milestone
    default: true
  plsdonate.donate.history:
    description: View your own donation history
    default: true
  plsdonate.donate.history.others:
    description: View another player's donation history
    default: op
  plsdonate.donate.help:
    description: View the /donate help message
    default: true
  plsdonate.donate.bypasscooldown:
    description: Bypass the /donate cooldown
    default: op
  plsdonate.admin.help:
    description: View admin commands in /pdn help
    default: op
  plsdonate.admin.transaction:
    description: Manage transaction records
    default: op
  plsdonate.admin.fakedonate:
    description: Simulate a sandbox donation
    default: op
  plsdonate.admin.pushdonate:
    description: Simulate a real donation
    default: op
  plsdonate.admin.testdiscord:
    description: Send a test Discord webhook embed
    default: op
  plsdonate.admin.reload:
    description: Reload the plugin configuration
    default: op
